[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
my_vault_program = "DsAYjtNg2xrV1xVcXNdXGB49mCJAfUnubq1jsZMNuawn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet" 
wallet = "~/.config/solana/localnet-keypair.json" 

# Devnet keypair path (for reference):
# wallet = "/home/solid/solana_keypair.json"
# LocalHost keypair path
# wallet = "~/.config/solana/localnet-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
